In [1]:
print(0)

0

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler,OneHotEncoder
import pickle

In [3]:
data =pd.read_csv('churn.csv')

In [4]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [6]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [7]:
label_gen=LabelEncoder()
data['Gender']=label_gen.fit_transform(data['Gender'])

In [8]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [9]:
ohe_geo=OneHotEncoder()
geo_encoded=ohe_geo.fit_transform(data[['Geography']]).toarray()
geo_df=pd.DataFrame(geo_encoded,columns=ohe_geo.get_feature_names_out(['Geography']))

In [10]:
data=pd.concat([data.drop('Geography',axis=1),geo_df],axis=1)

In [11]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [12]:
#splitting the data into independent and dependent features 
x=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [14]:
with open('label_gen.pkl','wb') as file:
    pickle.dump(label_gen,file)
    
with open('geo.pkl','wb') as file:
    pickle.dump(ohe_geo,file)

with open('stdscaler2.pkl','wb') as file:
    pickle.dump(scaler,file)

## ANN regression problem statement

In [15]:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import tensorflow as tf

In [16]:
model = Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1)# output layer for regression 
])

c:\Users\dipes\OneDrive\Desktop\ANNRNNproj\annenv\Lib\site-packages\keras\src\layers\core\dense.py:102: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [17]:
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tb_callback = TensorBoard(
    log_dir=log_dir,
    histogram_freq=1
)

In [19]:
# early stopping setup 
early_stopping_callbacks= EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [20]:
history  = model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=100,callbacks=[early_stopping_callbacks,tb_callback])

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 100369.7891 - mae: 100369.7891 - val_loss: 98488.2266 - val_mae: 98488.2266
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 99535.9766 - mae: 99535.9766 - val_loss: 96811.2031 - val_mae: 96811.2031
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 96650.7734 - mae: 96650.7734 - val_loss: 92587.9922 - val_mae: 92587.9922
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 91039.5859 - mae: 91039.5859 - val_loss: 85644.9609 - val_mae: 85644.9609
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 82985.5156 - mae: 82985.5156 - val_loss: 76881.7891 - val_mae: 76881.7891
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 73680.0078 - mae: 73680.0078 - val_loss: 67865.1953 - val_mae: 67865.1953
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64841.8945 - mae: 64841.8945 - val_loss: 60193.4258 - val_mae: 60193.4258
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 58020.1875 - mae: 58020.1875 - val_loss: 54920.7031 - val_mae: 54920.7031
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 53749.7695 - mae: 53749.7695 - val_loss: 52088.8672 - val_mae: 52088.8672
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 51607.4258 - mae: 51607.4258 - val_loss: 50951.8164 - val_mae: 50951.8164
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50696.0195 - mae: 50696.0195 - val_loss: 50566.6172 - val_mae: 50566.6172
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50335.1445 - mae: 50335.1445 - val_loss: 50470.6406 - val_mae: 50470.6406
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50185.3125 - mae: 50185.3125 - val_loss: 50424.4688 - val_mae: 50424.4688
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50102.4023 - mae: 50102.4023 - val_loss: 50395.4102 - val_mae: 50395.4102
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50045.9727 - mae: 50045.9727 - val_loss: 50373.5781 - val_mae: 50373.5781
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50000.7539 - mae: 50000.7539 - val_loss: 50352.6406 - val_mae: 50352.6406
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49962.9336 - mae: 49962.9336 - val_loss: 50334.0781 - val_mae: 50334.0781
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49929.4531 - mae: 49929.4531 - val_loss: 50319.1328 - val_mae: 50319.1328
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49899.5742 - mae: 49899.5742 - val_loss: 50305.6133 - val_mae: 50305.6133
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49872.5703 - mae: 49872.5703 - val_loss: 50294.5547 - val_mae: 50294.5547
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49847.4688 - mae: 49847.4688 - val_loss: 50283.5586 - val_mae: 50283.5586
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49824.8438 - mae: 49824.8438 - val_loss: 50273.1602 - val_mae: 50273.1602
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49803.9727 - mae: 49803.9727 - val_loss: 50263.6875 - val_mae: 50263.6875
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49784.5977 - mae: 49784.5977 - val_loss: 50257.5039 - val_mae: 50257.5039
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49766.2656 - mae: 49766.2656 - val_loss: 50252.6055 - val_mae: 50252.6055
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49748.5391 - mae: 49748.5391 - val_loss: 50248.6250 - val_mae: 50248.6250
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49731.4883 - mae: 49731.4883 - val_loss: 50244.6875 - val_mae: 50244.6875
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49716.1641 - mae: 49716.1641 - val_loss: 50240.6641 - val_mae: 50240.6641
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49701.1797 - mae: 49701.1797 - val_loss: 50236.8438 - val_mae: 50236.8438
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49686.9805 - mae: 49686.9805 - val_loss: 50235.4336 - val_mae: 50235.4336
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49672.9492 - mae: 49672.9492 - val_loss: 50231.4609 - val_mae: 50231.4609
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49659.8945 - mae: 49659.8945 - val_loss: 50230.5430 - val_mae: 50230.5430
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49647.1133 - mae: 49647.1133 - val_loss: 50230.5352 - val_mae: 50230.5352
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49634.9883 - mae: 49634.9883 - val_loss: 50229.9297 - val_mae: 50229.9297
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49623.0625 - mae: 49623.0625 - val_loss: 50232.2461 - val_mae: 50232.2461
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49612.0195 - mae: 49612.0195 - val_loss: 50233.7773 - val_mae: 50233.7773
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49601.8047 - mae: 49601.8047 - val_loss: 50234.2812 - val_mae: 50234.2812
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49591.9844 - mae: 49591.9844 - val_loss: 50234.7930 - val_mae: 50234.7930
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49582.6562 - mae: 49582.6562 - val_loss: 50233.8320 - val_mae: 50233.8320

In [21]:
%load_ext tensorboard

In [22]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6007 (pid 19372), started 14:13:44 ago. (Use '!kill 19372' to kill it.)

In [25]:
#evaluate the model for test data 
test_loss,test_mae=model.evaluate(x_test,y_test)
print(f"test mae : {test_mae}")
print(f"test loss : {test_loss}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 50229.9297 - mae: 50229.9297
test mae : 50229.9296875
test loss : 50229.9296875

In [26]:
model.save('regression.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.